### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by marcosci** [marcosci/landscapemetrics#26]
We should mention somewhere on the homepage that computing a lot of metrics (especially if you parallelize your code) creates a lot of copies of the rasters, so setting:

```r
options(rasterMaxMemory = nbytes)
```
... can save some time finding out why RStudio freezes every now and then.

**Comment by mhesselbarth** [comment]
Even without parallelizing R crashes quite fast

**Comment by Nowosad** [comment]
What's a role of this option here? Can you give me any example?

**Comment by mhesselbarth** [comment]
Well....we are not quite sure at the moment what exactly the problem is. One would just execute the line at the beginning of a script to increase the RAM the `raster` package is allowed to use (e.g. `options(rasterMaxMemory = 1e10)` for 10 GB RAM). However, I tracked the RAM and it is actually basically empty, however, RStudio crashes. Not really sure what the reason is though,,,

**Comment by Nowosad** [comment]
Have you tried executing it outside of RStudio?

**Comment by mhesselbarth** [comment]
@marcosci  recommended to use the jobs-tool of the newest RStudio version which is kind of doing it outside RStudio
